name: Documentation 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout ${{ matrix.python-version }}
      uses: actions/checkout@v2.3.1 
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
        pip install portray
        pip uninstall -y pdocs docstring_parser
        pip install git+git://github.com/EmGarr/docstring_parser.git git+git://github.com/EmGarr/pdocs.git

    - name: Documentation 
      run: |
        portray as_html -m src/kerod
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site/ # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
